// Textos, colores y estructura por defecto de cada tipo de negocio.
// Cualquier campo se puede sobrescribir desde el JSON del negocio.
//
// En los titulares, "|" separa la parte que se pinta en el color de acento:
//   'Fontanero en {ciudad}|sin sorpresas en la factura'
// Variables disponibles en todos los textos: {nombre}, {ciudad}, {actividad}, {profesion}.
//
// Los textos están escritos para no prometer nada que el negocio no haya confirmado:
// son una propuesta que se revisa con el dueño antes de publicar.

const PASOS = {
  domicilio: [
    { titulo: 'Nos cuentas qué pasa', texto: 'Por teléfono o por WhatsApp. Si puedes, mándanos una foto y lo vemos antes de ir.' },
    { titulo: 'Te damos el precio', texto: 'Presupuesto claro y sin compromiso. No empezamos nada sin que sepas lo que cuesta.' },
    { titulo: 'Lo dejamos resuelto', texto: 'Trabajo limpio, con factura y garantía. Si algo falla, volvemos.' },
  ],
  local: [
    { titulo: 'Reserva tu hora', texto: 'Por teléfono o por WhatsApp, cuando mejor te venga.' },
    { titulo: 'Te asesoramos', texto: 'Hablamos de lo que quieres antes de empezar, sin prisas.' },
    { titulo: 'Disfruta del resultado', texto: 'Y si algo no te convence, lo arreglamos.' },
  ],
  clinica: [
    { titulo: 'Pide tu cita', texto: 'Por teléfono o por WhatsApp. Te buscamos el hueco que mejor te encaje.' },
    { titulo: 'Valoramos tu caso', texto: 'Te escuchamos, te exploramos y te explicamos qué te pasa con palabras claras.' },
    { titulo: 'Un plan a tu medida', texto: 'Sabrás cuántas sesiones necesitas y cuánto cuesta antes de empezar.' },
  ],
};

export const SECTORES = {
  fontaneria: {
    actividad: 'Fontanería', profesion: 'Fontanero',
    estilo: 'rotulo', modo: 'domicilio', schema: 'Plumber', icono: 'droplets',
    paleta: { marca: '#0A5BC4', oscuro: '#0B2E59', acento: '#FFB000', fondo: '#F3F7FC', tinta: '#0F1B2D' },
    titular: 'Fontanero en {ciudad}|sin sorpresas en la factura',
    subtitular: 'Fugas, atascos, calentadores y reformas de baño. Te damos el precio antes de empezar y lo dejamos todo limpio al terminar.',
    cta: 'llamar',
    sellos: ['Presupuesto sin compromiso', 'Factura y garantía', 'Profesionales de {ciudad}'],
    servicios: [
      { icono: 'droplets', titulo: 'Fugas y humedades', texto: 'Localizamos la fuga y la reparamos con la menor obra posible.' },
      { icono: 'wrench', titulo: 'Desatascos', texto: 'Fregaderos, inodoros, duchas y bajantes, sin olores ni chapuzas.' },
      { icono: 'flame', titulo: 'Calentadores y termos', texto: 'Instalación, cambio y reparación de calentadores y termos eléctricos.' },
      { icono: 'bath', titulo: 'Reforma de baño', texto: 'Cambiamos la bañera por plato de ducha y renovamos el baño en pocos días.' },
      { icono: 'shower-head', titulo: 'Grifería y sanitarios', texto: 'Montaje y cambio de grifos, inodoros, lavabos y mamparas.' },
      { icono: 'siren', titulo: 'Averías urgentes', texto: 'Si se te inunda la casa, llámanos y te decimos al momento cuándo podemos ir.' },
    ],
    pasos: PASOS.domicilio,
    faqs: [
      { p: '¿Cobráis por venir a ver la avería?', r: 'Te lo decimos antes de ir. Muchas veces podemos orientarte por teléfono o con una foto por WhatsApp.' },
      { p: '¿Trabajáis con seguros de hogar?', r: 'Podemos trabajar con tu seguro o de forma particular, como prefieras. Pregúntanos por tu compañía.' },
      { p: '¿Dais factura y garantía?', r: 'Siempre. Todos los trabajos llevan factura y garantía por escrito.' },
      { p: '¿En qué zonas trabajáis?', r: 'En {zona}. Si estás un poco más lejos, llámanos y lo vemos.' },
    ],
    mensajeWhatsapp: 'Hola, os escribo desde vuestra web. Necesito un fontanero para ',
    cierre: '¿Necesitas un fontanero en {ciudad}?',
  },

  electricidad: {
    actividad: 'Electricidad', profesion: 'Electricista',
    estilo: 'rotulo', modo: 'domicilio', schema: 'Electrician', icono: 'zap',
    paleta: { marca: '#1E2A44', oscuro: '#141C2E', acento: '#F5C518', fondo: '#F5F6F3', tinta: '#161B26' },
    titular: 'Electricista en {ciudad}|trabajo limpio y precio cerrado',
    subtitular: 'Averías, cuadros eléctricos, boletines y cargadores para coche eléctrico. Te explicamos qué pasa y cuánto cuesta antes de tocar nada.',
    cta: 'llamar',
    sellos: ['Presupuesto sin compromiso', 'Factura y garantía', 'Profesionales de {ciudad}'],
    servicios: [
      { icono: 'zap', titulo: 'Averías eléctricas', texto: 'Saltan los plomos o una zona se queda sin luz: encontramos el fallo y lo arreglamos.' },
      { icono: 'settings', titulo: 'Cuadros eléctricos', texto: 'Renovación de cuadros, diferenciales y magnetotérmicos según normativa.' },
      { icono: 'file-check', titulo: 'Boletines y certificados', texto: 'Certificado de instalación para dar de alta la luz, cambiar la potencia o vender.' },
      { icono: 'plug-zap', titulo: 'Cargadores de coche eléctrico', texto: 'Puntos de recarga en garaje particular o comunitario.' },
      { icono: 'lightbulb', titulo: 'Iluminación LED', texto: 'Cambiamos tu iluminación a LED para ver mejor y pagar menos.' },
      { icono: 'solar-panel', titulo: 'Placas solares', texto: 'Estudio y montaje de autoconsumo para casas y negocios.' },
    ],
    pasos: PASOS.domicilio,
    faqs: [
      { p: '¿Hacéis el boletín eléctrico?', r: 'Sí. Hacemos el certificado de instalación eléctrica (el antiguo boletín) para altas, cambios de potencia y ventas.' },
      { p: '¿Cuánto se tarda en instalar un cargador para el coche?', r: 'Normalmente una jornada. Antes revisamos tu instalación y te damos un precio cerrado.' },
      { p: '¿Trabajáis para comunidades y negocios?', r: 'Sí, también hacemos instalaciones y mantenimiento en comunidades de vecinos, locales y oficinas.' },
      { p: '¿En qué zonas trabajáis?', r: 'En {zona}. Si estás un poco más lejos, llámanos y lo vemos.' },
    ],
    mensajeWhatsapp: 'Hola, os escribo desde vuestra web. Necesito un electricista para ',
    cierre: '¿Necesitas un electricista en {ciudad}?',
  },

  reformas: {
    actividad: 'Reformas', profesion: 'Reformas',
    estilo: 'rotulo', modo: 'domicilio', schema: 'GeneralContractor', icono: 'hard-hat',
    paleta: { marca: '#C2410C', oscuro: '#33241B', acento: '#FDBA74', fondo: '#F7F5F2', tinta: '#231A14' },
    titular: 'Reformas en {ciudad}|con un solo responsable de principio a fin',
    subtitular: 'Baños, cocinas y reformas integrales. Presupuesto detallado por partidas y un calendario por escrito antes de empezar.',
    cta: 'whatsapp',
    sellos: ['Presupuesto por partidas', 'Plazos por escrito', 'Factura y garantía'],
    servicios: [
      { icono: 'bath', titulo: 'Baños', texto: 'Renovación completa: fontanería, alicatado, plato de ducha y mueble.' },
      { icono: 'chef-hat', titulo: 'Cocinas', texto: 'Cocinas a medida, desde la obra hasta el último tirador.' },
      { icono: 'house', titulo: 'Reformas integrales', texto: 'Pisos y casas completos, con un único responsable de principio a fin.' },
      { icono: 'paint-roller', titulo: 'Pintura', texto: 'Interiores y fachadas, protegiendo muebles y limpiando al terminar.' },
      { icono: 'layout-grid', titulo: 'Suelos y alicatados', texto: 'Porcelánico, tarima y microcemento con acabados cuidados.' },
      { icono: 'hammer', titulo: 'Pequeñas obras', texto: 'Tabiques, falsos techos, puertas y arreglos que nadie quiere hacer.' },
    ],
    pasos: [
      { titulo: 'Visita sin compromiso', texto: 'Vamos a verlo, tomamos medidas y escuchamos lo que quieres.' },
      { titulo: 'Presupuesto por partidas', texto: 'Sabrás qué se hace, con qué materiales y cuánto cuesta cada cosa.' },
      { titulo: 'Obra con calendario', texto: 'Fechas por escrito y un único responsable al que llamar.' },
    ],
    faqs: [
      { p: '¿Cuánto cuesta reformar un baño?', r: 'Depende del tamaño y de los materiales. Vamos a verlo sin compromiso y te damos un presupuesto detallado por partidas.' },
      { p: '¿Cuánto tarda una reforma?', r: 'Un baño suele estar listo en una o dos semanas. Antes de empezar te damos el calendario por escrito.' },
      { p: '¿Os encargáis de los permisos?', r: 'Te ayudamos con la licencia o la declaración responsable que pida tu ayuntamiento.' },
      { p: '¿Puedo seguir viviendo en casa durante la obra?', r: 'En reformas parciales, sí. Protegemos el resto de la casa y recogemos cada día.' },
    ],
    mensajeWhatsapp: 'Hola, os escribo desde vuestra web. Quería pedir presupuesto para reformar ',
    cierre: '¿Pensando en reformar en {ciudad}?',
  },

  cerrajeria: {
    actividad: 'Cerrajería', profesion: 'Cerrajero',
    estilo: 'rotulo', modo: 'domicilio', schema: 'Locksmith', icono: 'key-round',
    paleta: { marca: '#0F5E63', oscuro: '#0B3336', acento: '#F2B705', fondo: '#F2F6F6', tinta: '#0F2224' },
    titular: 'Cerrajero en {ciudad}|rápido y sin romper',
    subtitular: 'Aperturas de puertas, cambios de cerradura y bombines de seguridad. Te decimos el precio por teléfono antes de salir.',
    cta: 'llamar',
    sellos: ['Precio antes de salir', 'Factura y garantía', 'Profesionales de {ciudad}'],
    servicios: [
      { icono: 'door-open', titulo: 'Apertura de puertas', texto: 'Si te has quedado fuera, abrimos sin romper en la mayoría de los casos.' },
      { icono: 'key-round', titulo: 'Cambio de cerradura', texto: 'Cambiamos cerradura o bombín si te mudas o pierdes las llaves.' },
      { icono: 'lock-keyhole', titulo: 'Bombines de seguridad', texto: 'Antibumping y antiextracción, para que no te abran en segundos.' },
      { icono: 'shield-check', titulo: 'Puertas acorazadas', texto: 'Instalación y reparación de puertas blindadas y acorazadas.' },
      { icono: 'store', titulo: 'Cierres de locales', texto: 'Persianas metálicas, cierres y candados para locales y naves.' },
      { icono: 'siren', titulo: 'Urgencias', texto: 'Te decimos por teléfono el precio y cuánto tardamos en llegar.' },
    ],
    pasos: PASOS.domicilio,
    faqs: [
      { p: '¿Cuánto cuesta abrir una puerta?', r: 'Depende de la hora y del tipo de cerradura. Te damos el precio por teléfono antes de salir.' },
      { p: '¿Rompéis la cerradura para abrir?', r: 'En la mayoría de los casos abrimos sin romper. Si hay que cambiar el bombín, te lo decimos antes.' },
      { p: '¿Qué bombín me recomendáis?', r: 'Uno con protección antibumping y antiextracción. Te explicamos las opciones según tu puerta.' },
      { p: '¿Me cubre el seguro de hogar?', r: 'Muchos seguros cubren la apertura de puertas. Te ayudamos con lo que te pidan.' },
    ],
    mensajeWhatsapp: 'Hola, os escribo desde vuestra web. Necesito un cerrajero para ',
    cierre: '¿Necesitas un cerrajero en {ciudad}?',
  },

  climatizacion: {
    actividad: 'Climatización', profesion: 'Aire acondicionado',
    estilo: 'rotulo', modo: 'domicilio', schema: 'HVACBusiness', icono: 'snowflake',
    paleta: { marca: '#0369A1', oscuro: '#0C2D48', acento: '#FB8C3C', fondo: '#F2F7FB', tinta: '#0E1F2E' },
    titular: 'Aire acondicionado en {ciudad}|instalado, revisado y funcionando',
    subtitular: 'Instalación, mantenimiento y reparación de aire acondicionado, aerotermia y calefacción. Te asesoramos sin compromiso.',
    cta: 'llamar',
    sellos: ['Asesoramiento sin compromiso', 'Factura y garantía', 'Profesionales de {ciudad}'],
    servicios: [
      { icono: 'snowflake', titulo: 'Instalación de aire acondicionado', texto: 'Te ayudamos a elegir el equipo adecuado y lo instalamos en un día.' },
      { icono: 'wrench', titulo: 'Mantenimiento y limpieza', texto: 'Filtros limpios y equipo revisado para que enfríe mejor y gaste menos.' },
      { icono: 'thermometer', titulo: 'Reparación de averías', texto: 'Si no enfría, gotea o hace ruido, lo diagnosticamos y lo reparamos.' },
      { icono: 'heater', titulo: 'Aerotermia', texto: 'Calefacción y agua caliente con aerotermia, la opción más eficiente.' },
      { icono: 'flame', titulo: 'Calderas y calefacción', texto: 'Instalación, revisión y reparación de calderas y radiadores.' },
      { icono: 'fan', titulo: 'Ventilación', texto: 'Extracción y ventilación para cocinas, baños y locales.' },
    ],
    pasos: PASOS.domicilio,
    faqs: [
      { p: '¿Qué aparato me conviene?', r: 'Depende de los metros, la orientación y el uso. Te asesoramos para que no te quedes corto ni pagues de más.' },
      { p: '¿Cada cuánto hay que hacer el mantenimiento?', r: 'Lo ideal es una revisión al año, antes del verano, para que enfríe bien y consuma menos.' },
      { p: '¿Instaláis cualquier marca?', r: 'Trabajamos con las principales marcas y te recomendamos la que mejor encaja con tu presupuesto.' },
      { p: '¿En qué zonas trabajáis?', r: 'En {zona}. Si estás un poco más lejos, llámanos y lo vemos.' },
    ],
    mensajeWhatsapp: 'Hola, os escribo desde vuestra web. Quería información sobre ',
    cierre: '¿Calor en casa? Te lo solucionamos en {ciudad}',
  },

  taller: {
    actividad: 'Taller mecánico', profesion: 'Taller mecánico',
    estilo: 'rotulo', modo: 'local', schema: 'AutoRepair', icono: 'car',
    paleta: { marca: '#B91C1C', oscuro: '#1F1A17', acento: '#F59E0B', fondo: '#F6F5F4', tinta: '#1C1917' },
    titular: 'Taller mecánico en {ciudad}|presupuesto antes de tocar nada',
    subtitular: 'Mantenimiento, frenos, neumáticos, diagnosis y pre-ITV para todas las marcas. Te llamamos con el precio antes de reparar.',
    cta: 'llamar',
    sellos: ['Presupuesto antes de reparar', 'Todas las marcas', 'Factura y garantía'],
    servicios: [
      { icono: 'wrench', titulo: 'Mantenimiento y revisiones', texto: 'Aceite y filtros con el plan de tu fabricante, sin perder la garantía.' },
      { icono: 'disc', titulo: 'Frenos', texto: 'Pastillas, discos y líquido de frenos revisados para que frenes seguro.' },
      { icono: 'circle-gauge', titulo: 'Neumáticos', texto: 'Venta, montaje, equilibrado y alineación de neumáticos.' },
      { icono: 'gauge', titulo: 'Diagnosis', texto: '¿Se ha encendido un testigo? Leemos la centralita y te explicamos qué pasa.' },
      { icono: 'file-check', titulo: 'Pre-ITV', texto: 'Revisamos el coche antes de la ITV para que pase a la primera.' },
      { icono: 'snowflake', titulo: 'Aire acondicionado', texto: 'Carga de gas y reparación del aire acondicionado del coche.' },
    ],
    pasos: [
      { titulo: 'Pide cita', texto: 'Llámanos o escríbenos y te decimos cuándo puedes traer el coche.' },
      { titulo: 'Te llamamos con el precio', texto: 'Revisamos el coche y no tocamos nada sin que lo apruebes.' },
      { titulo: 'Recógelo listo', texto: 'Te avisamos cuando esté y te explicamos lo que se ha hecho.' },
    ],
    faqs: [
      { p: '¿Pierdo la garantía si no voy al concesionario?', r: 'No. Si el mantenimiento sigue el plan del fabricante, conservas la garantía aunque lo hagas en un taller independiente.' },
      { p: '¿Me dais presupuesto antes de reparar?', r: 'Siempre. No tocamos nada sin que sepas antes qué vamos a hacer y cuánto cuesta.' },
      { p: '¿Cuánto tarda una revisión?', r: 'La mayoría están listas en el día. Te avisamos en cuanto puedas recoger el coche.' },
      { p: '¿Trabajáis con todas las marcas?', r: 'Sí: turismos de todas las marcas, gasolina, diésel e híbridos.' },
    ],
    mensajeWhatsapp: 'Hola, os escribo desde vuestra web. Quería pedir cita para mi coche: ',
    cierre: '¿Toca revisión? Trae tu coche',
  },

  barberia: {
    actividad: 'Barbería', profesion: 'Barbería',
    estilo: 'salon', modo: 'local', schema: 'HairSalon', icono: 'scissors',
    paleta: { marca: '#1F3D2B', oscuro: '#13261B', acento: '#C8A45C', fondo: '#F1F4F1', tinta: '#18201B' },
    titular: 'Barbería en {ciudad}|reserva tu hora y no esperes',
    subtitular: 'Cortes clásicos y modernos, arreglo de barba con toalla caliente y afeitado a navaja. Atención sin prisas.',
    cta: 'reservar',
    sellos: ['Reserva por WhatsApp', 'Tarjeta y Bizum', 'Atención sin prisas'],
    servicios: [
      { icono: 'scissors', titulo: 'Corte de pelo', texto: 'Clásico, degradado o a tijera, según tu pelo y tu estilo.' },
      { icono: 'droplet', titulo: 'Arreglo de barba', texto: 'Perfilado con toalla caliente, aceites y navaja.' },
      { icono: 'sparkles', titulo: 'Afeitado clásico', texto: 'Afeitado a navaja con espuma caliente y bálsamo.' },
      { icono: 'crown', titulo: 'Corte y barba', texto: 'El servicio completo, para salir como nuevo.' },
      { icono: 'palette', titulo: 'Color y canas', texto: 'Matizamos las canas con un resultado natural.' },
      { icono: 'baby', titulo: 'Corte infantil', texto: 'Paciencia y buen pulso para los más pequeños.' },
    ],
    pasos: PASOS.local,
    faqs: [
      { p: '¿Hace falta reservar?', r: 'Te lo recomendamos para no esperar, pero si hay hueco te atendemos al momento.' },
      { p: '¿Cuánto dura un corte?', r: 'Unos 30 minutos. Con barba, cuenta con 45.' },
      { p: '¿Cortáis a niños?', r: 'Sí, con paciencia y buen pulso.' },
      { p: '¿Cómo se puede pagar?', r: 'Con tarjeta, Bizum o en efectivo.' },
    ],
    mensajeWhatsapp: 'Hola, quería reservar hora para ',
    cierre: '¿Te reservamos hora?',
  },

  peluqueria: {
    actividad: 'Peluquería', profesion: 'Peluquería',
    estilo: 'salon', modo: 'local', schema: 'HairSalon', icono: 'scissors',
    paleta: { marca: '#7C3A5B', oscuro: '#3A1B2B', acento: '#E8B4A0', fondo: '#FAF6F8', tinta: '#2A1721' },
    titular: 'Peluquería en {ciudad}|el pelo que de verdad te queda bien',
    subtitular: 'Corte, color, mechas y tratamientos. Te asesoramos antes de empezar para que salgas encantada con el resultado.',
    cta: 'reservar',
    sellos: ['Cita por WhatsApp', 'Productos profesionales', 'Tarjeta y Bizum'],
    servicios: [
      { icono: 'scissors', titulo: 'Corte y peinado', texto: 'Cortes de mujer, hombre y niños, pensados para tu día a día.' },
      { icono: 'palette', titulo: 'Color', texto: 'Tintes, cobertura de canas y cambios de look con color que dura.' },
      { icono: 'sparkles', titulo: 'Mechas y balayage', texto: 'Mechas, balayage y babylights con un acabado natural.' },
      { icono: 'droplet', titulo: 'Tratamientos', texto: 'Hidratación, keratina y tratamientos para recuperar el pelo dañado.' },
      { icono: 'wind', titulo: 'Peinados de fiesta', texto: 'Recogidos y peinados para bodas, comuniones y celebraciones.' },
      { icono: 'flower-2', titulo: 'Novias', texto: 'Prueba previa y peinado el día de la boda, sin prisas.' },
    ],
    pasos: PASOS.local,
    faqs: [
      { p: '¿Necesito cita?', r: 'Sí, trabajamos con cita para atenderte sin prisas. Reserva por teléfono o por WhatsApp.' },
      { p: '¿Hacéis prueba antes de un cambio de color?', r: 'Antes de un cambio grande te asesoramos y, si hace falta, hacemos una prueba.' },
      { p: '¿Qué productos usáis?', r: 'Productos profesionales que cuidan el pelo. Te decimos qué usar en casa para que el color dure.' },
      { p: '¿Hacéis peinados para bodas?', r: 'Sí. Consúltanos la fecha y te preparamos un presupuesto con prueba incluida.' },
    ],
    mensajeWhatsapp: 'Hola, quería pedir cita para ',
    cierre: '¿Te damos cita?',
  },

  estetica: {
    actividad: 'Centro de estética', profesion: 'Centro de estética',
    estilo: 'salon', modo: 'local', schema: 'BeautySalon', icono: 'sparkles',
    paleta: { marca: '#4F7563', oscuro: '#22362C', acento: '#D9A25F', fondo: '#F4F7F5', tinta: '#1B2621' },
    titular: 'Centro de estética en {ciudad}|un rato para ti, en buenas manos',
    subtitular: 'Tratamientos faciales y corporales, depilación, manicura y pestañas. Te recomendamos lo que de verdad va con tu piel.',
    cta: 'reservar',
    sellos: ['Cita por WhatsApp', 'Bonos y tarjetas regalo', 'Tarjeta y Bizum'],
    servicios: [
      { icono: 'sparkles', titulo: 'Tratamientos faciales', texto: 'Limpieza facial, hidratación y tratamientos antiedad.' },
      { icono: 'leaf', titulo: 'Depilación', texto: 'Cera, hilo o láser, con el método que mejor va a tu piel.' },
      { icono: 'hand', titulo: 'Manicura y pedicura', texto: 'Manicura, esmaltado semipermanente y pedicura con acabado impecable.' },
      { icono: 'eye', titulo: 'Pestañas y cejas', texto: 'Lifting de pestañas, laminado y diseño de cejas.' },
      { icono: 'flower-2', titulo: 'Masajes', texto: 'Masajes relajantes y descontracturantes para desconectar.' },
      { icono: 'heart', titulo: 'Tratamientos corporales', texto: 'Tratamientos reafirmantes y drenantes adaptados a ti.' },
    ],
    pasos: PASOS.local,
    faqs: [
      { p: 'Nunca me he hecho un tratamiento, ¿por dónde empiezo?', r: 'Ven a una primera visita y te recomendamos lo que mejor va con tu piel y con lo que buscas.' },
      { p: '¿La depilación láser duele?', r: 'Se nota un pequeño pinchazo, muy llevadero. Ajustamos la potencia a tu piel.' },
      { p: '¿Tenéis bonos?', r: 'Sí, para los tratamientos de varias sesiones. Pregúntanos.' },
      { p: '¿Puedo regalar un tratamiento?', r: 'Claro, preparamos tarjetas regalo para cualquier ocasión.' },
    ],
    mensajeWhatsapp: 'Hola, quería pedir cita para ',
    cierre: '¿Te reservamos un hueco?',
  },

  fisioterapia: {
    actividad: 'Fisioterapia', profesion: 'Fisioterapia',
    estilo: 'clinica', modo: 'local', schema: 'Physiotherapy', icono: 'activity',
    paleta: { marca: '#0E7C86', oscuro: '#0B3B40', acento: '#F4A261', fondo: '#F2F8F8', tinta: '#10282B' },
    titular: 'Fisioterapia en {ciudad}|vuelve a moverte sin dolor',
    subtitular: 'Dolor de espalda, cervicales, lesiones deportivas y recuperación tras operaciones. Valoramos tu caso y te explicamos el plan.',
    cta: 'reservar',
    sellos: ['Fisioterapeutas colegiados', 'Sin volante médico', 'Cita por WhatsApp'],
    servicios: [
      { icono: 'activity', titulo: 'Dolor de espalda', texto: 'Lumbalgias, ciáticas y contracturas tratadas desde el origen.' },
      { icono: 'bone', titulo: 'Cervicales', texto: 'Dolor de cuello, mareos y dolores de cabeza de origen cervical.' },
      { icono: 'dumbbell', titulo: 'Lesiones deportivas', texto: 'Esguinces, roturas fibrilares y tendinitis, para que vuelvas a entrenar.' },
      { icono: 'accessibility', titulo: 'Rehabilitación', texto: 'Recuperación tras operaciones, fracturas y prótesis.' },
      { icono: 'hand', titulo: 'Masaje terapéutico', texto: 'Descarga muscular y masaje para aliviar tensiones.' },
      { icono: 'person-standing', titulo: 'Ejercicio terapéutico', texto: 'Te enseñamos ejercicios para que el dolor no vuelva.' },
    ],
    pasos: PASOS.clinica,
    faqs: [
      { p: '¿Necesito volante del médico?', r: 'No. Puedes venir directamente. Si tienes informes o pruebas, tráelos a la primera sesión.' },
      { p: '¿Cuántas sesiones voy a necesitar?', r: 'Depende de tu caso. En la primera sesión te explicamos el plan y lo revisamos según evoluciones.' },
      { p: '¿Qué ropa llevo?', r: 'Ropa cómoda. Si vienes por la pierna o la rodilla, mejor pantalón corto.' },
      { p: '¿Trabajáis con mutuas o seguros?', r: 'Consúltanos: trabajamos de forma privada y con algunas compañías.' },
    ],
    mensajeWhatsapp: 'Hola, quería pedir cita de fisioterapia para ',
    cierre: '¿Te damos cita esta semana?',
  },

  dental: {
    actividad: 'Clínica dental', profesion: 'Clínica dental',
    estilo: 'clinica', modo: 'local', schema: 'Dentist', icono: 'smile',
    paleta: { marca: '#3B5BDB', oscuro: '#1A2459', acento: '#63E6BE', fondo: '#F5F7FF', tinta: '#141B34' },
    titular: 'Clínica dental en {ciudad}|sabrás el precio antes de empezar',
    subtitular: 'Revisiones, limpiezas, empastes, ortodoncia e implantes. Te explicamos el tratamiento con calma y sin letra pequeña.',
    cta: 'reservar',
    sellos: ['Precio antes de empezar', 'Facilidades de pago', 'Cita por WhatsApp'],
    servicios: [
      { icono: 'stethoscope', titulo: 'Revisión y limpieza', texto: 'Revisión completa y limpieza profesional para prevenir problemas.' },
      { icono: 'shield-plus', titulo: 'Empastes y endodoncias', texto: 'Tratamos las caries a tiempo para salvar tus dientes.' },
      { icono: 'smile', titulo: 'Ortodoncia', texto: 'Brackets y ortodoncia invisible para niños y adultos.' },
      { icono: 'sparkles', titulo: 'Blanqueamiento', texto: 'Dientes más blancos con un tratamiento seguro y supervisado.' },
      { icono: 'shield-check', titulo: 'Implantes', texto: 'Recupera las piezas que te faltan con implantes de calidad.' },
      { icono: 'baby', titulo: 'Odontopediatría', texto: 'Cuidamos la boca de los peques desde su primera visita.' },
    ],
    pasos: [
      { titulo: 'Pide tu cita', texto: 'Por teléfono o por WhatsApp, en el horario que mejor te venga.' },
      { titulo: 'Revisión y diagnóstico', texto: 'Te explicamos lo que vemos, con imágenes y sin tecnicismos.' },
      { titulo: 'Presupuesto claro', texto: 'Sabrás el precio y las opciones de pago antes de empezar.' },
    ],
    faqs: [
      { p: '¿Cuánto cuesta una limpieza?', r: 'Te lo decimos al pedir cita. Siempre sabrás el precio antes de empezar cualquier tratamiento.' },
      { p: '¿Se puede pagar a plazos?', r: 'Consúltanos las opciones de pago a plazos para los tratamientos más grandes.' },
      { p: '¿Atendéis urgencias?', r: 'Si te duele, llámanos: hacemos lo posible por verte el mismo día.' },
      { p: '¿A qué edad debe ir un niño al dentista?', r: 'Recomendamos una primera revisión hacia los 3 años, o antes si notas algo.' },
    ],
    mensajeWhatsapp: 'Hola, quería pedir cita en la clínica para ',
    cierre: '¿Hace cuánto no vas al dentista?',
  },

  restaurante: {
    actividad: 'Restaurante', profesion: 'Restaurante',
    estilo: 'salon', modo: 'local', schema: 'Restaurant', icono: 'utensils',
    paleta: { marca: '#3F4F1F', oscuro: '#232C11', acento: '#C93C22', fondo: '#F6F7F2', tinta: '#1E2414' },
    titular: 'Restaurante en {ciudad}|cocina de aquí, producto de temporada',
    antetituloServicios: 'La casa', tituloServicios: 'Lo que te espera en {nombre}',
    subtitular: 'Menú del día, carta de temporada y una mesa esperándote. Reserva por teléfono o por WhatsApp.',
    cta: 'reservar',
    sellos: ['Reserva por WhatsApp', 'Menús para grupos', 'Para llevar'],
    servicios: [
      { icono: 'utensils', titulo: 'Menú del día', texto: 'Cocina casera entre semana: primero, segundo y postre.' },
      { icono: 'fish', titulo: 'Pescado y marisco', texto: 'Producto fresco preparado al momento.' },
      { icono: 'chef-hat', titulo: 'Carta de temporada', texto: 'Platos que cambian con lo que da cada temporada.' },
      { icono: 'party-popper', titulo: 'Celebraciones', texto: 'Cumpleaños, comidas de empresa y reuniones familiares.' },
      { icono: 'hand-platter', titulo: 'Para llevar', texto: 'Haz tu pedido por teléfono y recógelo listo.' },
      { icono: 'wine', titulo: 'Bodega', texto: 'Vinos de la tierra y una selección pensada para cada plato.' },
    ],
    pasos: null, // en un restaurante no hay un proceso que contar
    faqs: [
      { p: '¿Hace falta reservar?', r: 'Los fines de semana, sí. Entre semana suele haber sitio, pero mejor avísanos.' },
      { p: '¿Tenéis opciones sin gluten o vegetarianas?', r: 'Sí. Avísanos al reservar y te recomendamos qué pedir.' },
      { p: '¿Hacéis menús para grupos?', r: 'Sí, preparamos menús cerrados para celebraciones y comidas de empresa.' },
      { p: '¿Se puede pedir para llevar?', r: 'Sí. Llámanos y te lo tenemos listo para recoger.' },
    ],
    mensajeWhatsapp: 'Hola, quería reservar mesa para ',
    cierre: '¿Te guardamos mesa?',
  },

  entrenador: {
    actividad: 'Entrenamiento personal', profesion: 'Entrenador personal',
    estilo: 'rotulo', modo: 'local', schema: 'HealthClub', icono: 'dumbbell',
    paleta: { marca: '#4338CA', oscuro: '#1E1B4B', acento: '#FB923C', fondo: '#F5F5FA', tinta: '#17162B' },
    titular: 'Entrenador personal en {ciudad}|resultados que se notan y se mantienen',
    subtitular: 'Entrenamiento a tu medida para perder grasa, ganar fuerza o volver a moverte sin dolor. Empezamos desde tu nivel.',
    cta: 'whatsapp',
    sellos: ['Sesión de valoración', 'Plan a tu medida', 'Seguimiento por WhatsApp'],
    servicios: [
      { icono: 'dumbbell', titulo: 'Entrenamiento personal', texto: 'Sesiones uno a uno con un plan hecho para ti.' },
      { icono: 'users', titulo: 'Grupos reducidos', texto: 'Entrena con dos a cuatro personas y comparte precio sin perder atención.' },
      { icono: 'apple', titulo: 'Nutrición', texto: 'Pautas de alimentación sencillas que puedas mantener.' },
      { icono: 'heart-pulse', titulo: 'Salud y dolor', texto: 'Ejercicio adaptado para espalda, rodillas o la vuelta tras una lesión.' },
      { icono: 'trophy', titulo: 'Rendimiento deportivo', texto: 'Preparación física para pádel, running, oposiciones y más.' },
      { icono: 'smartphone', titulo: 'Entrenamiento online', texto: 'Tu plan y tu seguimiento en el móvil, entrenes donde entrenes.' },
    ],
    pasos: [
      { titulo: 'Sesión de valoración', texto: 'Vemos de dónde partes, qué quieres conseguir y qué tiempo tienes.' },
      { titulo: 'Tu plan', texto: 'Entrenamiento y pautas a tu medida, que encajen en tu semana.' },
      { titulo: 'Seguimiento', texto: 'Medimos el progreso y ajustamos el plan para que no te estanques.' },
    ],
    faqs: [
      { p: '¿Necesito estar en forma para empezar?', r: 'No. Empezamos desde tu nivel, sea cual sea.' },
      { p: '¿Dónde son las sesiones?', r: 'En el centro, al aire libre o en tu casa, como mejor te venga.' },
      { p: '¿Cuántas sesiones a la semana?', r: 'Con dos sesiones semanales se notan resultados. Te ayudamos a encajarlas en tu agenda.' },
      { p: '¿Incluye plan de alimentación?', r: 'Te damos pautas sencillas que puedas seguir sin pasar hambre.' },
    ],
    mensajeWhatsapp: 'Hola, os escribo desde la web. Quería información sobre ',
    cierre: '¿Empezamos esta semana?',
  },

  generico: {
    actividad: 'Negocio local', profesion: 'Negocio local',
    estilo: 'clinica', modo: 'local', schema: 'LocalBusiness', icono: 'store',
    paleta: { marca: '#155E75', oscuro: '#0E3340', acento: '#F59E0B', fondo: '#F4F7F8', tinta: '#132227' },
    titular: '{nombre}|en {ciudad}',
    subtitular: 'Atención cercana y profesional en {ciudad}. Cuéntanos qué necesitas y te ayudamos.',
    cta: 'whatsapp',
    sellos: ['Atención personalizada', 'Respuesta en el día', 'Negocio de {ciudad}'],
    servicios: [
      { icono: 'badge-check', titulo: 'Atención personalizada', texto: 'Te escuchamos y te proponemos la mejor solución para tu caso.' },
      { icono: 'euro', titulo: 'Precios claros', texto: 'Sabrás lo que pagas antes de empezar.' },
      { icono: 'clock', titulo: 'Puntualidad', texto: 'Cumplimos los plazos y los horarios que te damos.' },
      { icono: 'map-pin', titulo: 'Cerca de ti', texto: 'Negocio local, en {ciudad} y alrededores.' },
      { icono: 'message-circle', titulo: 'Respuesta rápida', texto: 'Escríbenos por WhatsApp y te contestamos en el día.' },
      { icono: 'thumbs-up', titulo: 'Garantía', texto: 'Si algo no queda bien, lo solucionamos.' },
    ],
    pasos: null,
    faqs: [
      { p: '¿Cómo puedo pedir información?', r: 'Llámanos o escríbenos y te contestamos lo antes posible.' },
      { p: '¿Dónde estáis?', r: 'En {ciudad}. Tienes la dirección y el horario un poco más abajo.' },
      { p: '¿Hacéis presupuestos?', r: 'Sí, sin compromiso.' },
      { p: '¿Cómo se puede pagar?', r: 'En efectivo, con tarjeta o por Bizum.' },
    ],
    mensajeWhatsapp: 'Hola, os escribo desde vuestra web. Quería información sobre ',
    cierre: '¿Hablamos?',
  },
};

export const LISTA_SECTORES = Object.keys(SECTORES);
